# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_info', models.CharField(max_length=200)),
                ('browser_info', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=10)),
                ('event_name', models.CharField(max_length=100)),
                ('visited_by', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
