# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitelogs',
            name='state_code',
            field=models.CharField(max_length=10),
        ),
    ]
