# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-02 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20200501_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelogs',
            name='unique_visit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
